### ISSUE TITLE
Fotmob - Commands

### ISSUE THREAD

**Issue by camilortega8** [JaseZiv/worldfootballR_data#20]
Hello, is the fotmob commands working? I am trying to use it, and did not manage to be working.

**Comment by tonyelhabr** [comment]
fotmob functionality was removed in [this PR](https://github.com/JaseZiv/worldfootballR/pull/311). You can still download data from [here](https://github.com/JaseZiv/worldfootballR_data/releases/tag/fotmob_match_details). You may be able to search Github and find another package that supports fotmob data retrieval.
