### ISSUE TITLE
FBref match shooting failures

### ISSUE THREAD

**Issue by tudor-postolache** [JaseZiv/worldfootballR_data#22]
Hi there,

I'm not a contributor, but I wanted to let you know that the FBRef match shooting data doesn't appear to have been updated or working since November 30th. Looking at the job history, it does appear that the last 3 have failed with the same error.

I'm a frequent user of the data and really appreciate the work you've put into this project. Just thought you'd like to know!

Thanks again for all your efforts!

**Comment by tonyelhabr** [comment]
Should be fixed now. Sorry, I had pushed a change last week, and didn't actually test it.

**Comment by tudor-postolache** [comment]
Thank you @tonyelhabr!

**Comment by tudor-postolache** [comment]
Hello,

Wanted to say that the match shooting workflow has been failing again for some time, it looks, was wondering if it is still maintained? Thanks again!
