### ISSUE TITLE
get_match_urls() for World Cup Qualifying

### ISSUE THREAD

**Issue by mattbarger** [JaseZiv/worldfootballR_data#6]
I'm finding that the `get_match_urls()` function does not work for the WCQ comp_urls listed.

I'd love to extract and clean data from the 2022 WCQ cycle just in time for the upcoming World Cup, any chance we could make this happen?

**Comment by JaseZiv** [comment]
Hi @mattbarger,

Can you please open this issue in the [worldfootballR](https://github.com/JaseZiv/worldfootballR/issues) repo issues?

Thanks in advance
